### ISSUE TITLE
Non issue

### ISSUE THREAD

**Issue by parrasajad** [kubernetes-sigs/execution-hook#1]
I would love to contibute to this project if some one can help me through at first

**Comment by nikhita** [comment]
@parrasajad Welcome! :tada:  

I'd suggest to join the sig-apps slack channels and mailing lists and join their weekly meetings. You can find information about these here: https://github.com/kubernetes/community/tree/master/sig-apps.

The quickest way to getting started would be to let folks know in the #sig-apps slack channel that you are interested and ask for potential tasks to contribute.

/close
